# {{game_name}}

```{r extract-data-{{game_name_abbr}}}
data <- indices_clean |>
  filter(
    game_name_abbr == "{{game_name_abbr}}",
    if_all(contains("test"), ~ !is.infinite(.x)),
    !(is.na(test) & is.na(retest))
  ) |>
  group_by(index_name) |>
  mutate(
    across(
      contains("test"),
      list(
        is_outlier = ~ .x %in% boxplot.stats(.x)$out
      )
    )
  ) |>
  ungroup() |>
  mutate(
    is_outlier = test_is_outlier | retest_is_outlier,
    .keep = "unused"
  )
n_indices <- n_distinct(data$index_name)
```

## Basic Information

* Abbreviation: {{game_name_abbr}}
* Sample Size: `r n_distinct(data$user_id)`
* Index Names:
`r str_c(str_c("  * ", unique(data$index_name)), collapse = "\n")`

## Pairwise Correlation of indices

```{r pairwise-{{game_name_abbr}}, fig.height=(6 * n_indices + 27) / 11, fig.width=(8 * n_indices + 36) / 11}
data |>
  pivot_wider(
    id_cols = user_id,
    names_from = index_name,
    values_from = test
  ) |>
  select(-user_id) |>
  GGally::ggpairs()
```

## Test-Retest

```{r test-retest-{{game_name_abbr}}, fig.height=4 * n_indices, fig.width=4}
data_test_retest <- drop_na(data)
reliability <- data_test_retest |>
  group_by(index_name) |>
  group_modify(
    ~ tibble(
      n = nrow(.x),
      n_no_outlier = .x |>
        filter(!is_outlier) |>
        nrow(),
      icc = .x |>
        select(contains("test")) |>
        psych::ICC() |>
        pluck("results", "ICC", 2),
      icc_no_outlier = .x |>
        filter(!is_outlier) |>
        select(contains("test")) |>
        psych::ICC() |>
        pluck("results", "ICC", 2),
      r = cor(.x$test, .x$retest),
      r_no_outlier = .x |>
        filter(!is_outlier) |>
        summarise(r = cor(test, retest)) |>
        pull(r)
    )
  ) |>
  ungroup()
data_test_retest |>
  ggpubr::ggscatter("test", "retest", color = "is_outlier") +
  geom_text(
    data = reliability,
    aes(
      x = -Inf, y = Inf,
      label = str_glue(
        "N = {n} ({n_no_outlier})\n",
        "r = {round(r, 2)} ({round(r_no_outlier, 2)})\n",
        "icc = {round(icc, 2)} ({round(icc_no_outlier, 2)})"
      )
    ),
    hjust = -0.1, vjust = 1.1
  ) +
  scale_color_grey() +
  facet_wrap(~ index_name, ncol = 1, scales = "free") +
  theme(aspect.ratio = 1) +
  labs(
    color = "Outlier",
    caption = "Values in brackets are those without outliers."
  )
```
