---
title: "BNU results"
output: html_document
# runtime: shiny
# redirect output to another folder (default is base_dir/output)
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = fs::path(here::here(), "output"),
      ...
    )
  })
---

```{r setup, include=FALSE}
library(targets)
knitr::opts_chunk$set(echo = TRUE, tar_interactive = FALSE)
targets::tar_unscript()
```

```{targets utils, tar_globals=TRUE, include=FALSE}
check_device <- function(dm) {
  key <- dm::dm_get_all_pks(dm, "meta") |> pluck("pk_col", 1)
  if (!has_name(dm::pull_tbl(dm, "data"), "device")) {
    dm <- dm |> 
      dm::dm_zoom_to("data") |> 
      dm::mutate(device = "mouse") |> 
      dm::dm_update_zoomed()
  }
  dm |> 
    dm::dm_zoom_to("data") |> 
    dm::group_by(across(all_of(key))) |> 
    dm::summarise(
      used_mouse = str_c(device, collapse = "-") |> 
        str_split("-") |> 
        map_lgl(~ any(.x == "mouse")), 
      .groups = "drop"
    ) |> 
    dm::dm_insert_zoomed("device_test") |> 
    dm::dm_select_tbl(-"data")
}
validate_data <- function(dm, name) {
  key <- dm::dm_get_all_pks(dm, "meta") |> pluck("pk_col", 1)
  if (name == "LdnTwr") {
    out <- dm |> 
      dm::dm_zoom_to("data") |> 
      dm::group_by(across(all_of(key))) |> 
      dm::summarise(valid_version = !anyNA(minmove), .groups = "drop") |> 
      dm::dm_insert_zoomed("validation")
  } else if (
    name %in% c("Grid2back", "Paint2back", "Digit3back", "Verbal3back")
  ) {
    out <- dm |> 
      dm::dm_zoom_to("data") |> 
      dm::group_by(across(all_of(key))) |> 
      dm::summarise(valid_version = any(type == "lure"), .groups = "drop") |> 
      dm::dm_insert_zoomed("validation")
  } else {
    out <- dm |> 
      dm::dm_zoom_to("data") |> 
      dm::group_by(across(all_of(key))) |> 
      dm::summarise(valid_version = TRUE, .groups = "drop") |> 
      dm::dm_insert_zoomed("validation")
  }
  out |> 
    dm::dm_select_tbl(-data)
}
combine_dm <- function(...) {
  list(...) |> 
    map(dm::dm_squash_to_tbl, start = "meta") |> 
    bind_rows(.id = "source") |> 
    extract(source, "game_name_abbr", "(?<=_)([^_]+$)")
}
clean_indices <- function(indices, file_keyboard, data_validation, device_info) {
  tests_keyboard <- read_lines(file_keyboard)
  validation <- device_info |> 
    mutate(valid_device = !(game_name %in% tests_keyboard & used_mouse)) |> 
    inner_join(data_validation) |> 
    filter(valid_device & valid_version) |> 
    group_by(user_id, game_name) |> 
    filter(
      if_else(
        str_detect(game_name_abbr, "[A|B]$"), 
        row_number(desc(game_time)) == 1,
        row_number(desc(game_time)) <= 2
      )
    ) |> 
    ungroup()
  indices |> 
    semi_join(validation) |> 
    mutate(across(starts_with("game_name"), ~ str_remove(.x, "[A|B]$"))) |> 
    group_by(user_id, game_name_abbr, game_name, index_name) |> 
    mutate(occasion = recode(row_number(game_time), `1` = "test", `2` = "retest")) |> 
    ungroup() |> 
    pivot_wider(
      id_cols = c(user_id, game_name, game_name_abbr, index_name), 
      names_from = occasion,
      values_from = score
    )
}
```

```{targets set-globals, tar_globals=TRUE, include=FALSE}
future::plan(future.callr::callr)
games <- tarflow.iquizoo::search_games_mem(config::get("where"))
tar_option_set(
  package = c("tidyverse", "preproc.iquizoo", "tarflow.iquizoo"),
  format = "qs",
  imports = "preproc.iquizoo"
)
targets_data <- tarchetypes::tar_map(
  values = games,
  names = game_name_abbr,
  # major targets
  tar_target(data, pickup(query_tmpl_data, config_where_single_game)),
  tar_target(data_parsed, wrangle_data(data, key)),
  tar_target(
    indices,
    preproc_data(data_parsed, prep_fun, .input = input, .extra = extra)
  ),
  tar_target(device_info, check_device(data_parsed)),
  tar_target(data_validation, validate_data(data_parsed, game_name_abbr)),
  # configurations
  tar_target(
    config_where_single_game,
    insert_where_single_game(config_where, game_id)
  ),
  tar_target(
    input,
    config::get("input", config = game_name_abbr, file = file_config)
  ),
  tar_target(
    extra,
    config::get("extra", config = game_name_abbr, file = file_config)
  )
)
```

```{targets load-config, include=FALSE}
list(
  tar_target(file_config, "config.yml", format = "file"),
  tar_target(config_where, config::get("where", file = file_config))
)
```

```{targets download-users, include=FALSE}
list(
  tar_target(query_tmpl_users, fs::path("sql", "users.tmpl.sql"), format = "file"),
  tar_target(users, tarflow.iquizoo::pickup(query_tmpl_users, config_where))
)
```

```{targets data-and-scores, include=FALSE}
list(
  tar_target(query_tmpl_data, fs::path("sql", "data.tmpl.sql"), format = "file"),
  tar_target(file_keyboard, "config/require_keybord.txt", format = "file"),
  tar_target(key, ".id"),
  targets_data,
  tarchetypes::tar_combine(data, targets_data[[1]]),
  tarchetypes::tar_combine(
    indices, 
    targets_data[[3]],
    command = combine_dm(!!!.x)
  ),
  tarchetypes::tar_combine(
    device_info,
    targets_data[[4]],
    command = combine_dm(!!!.x)
  ),
  tarchetypes::tar_combine(
    data_validation,
    targets_data[[5]],
    command = combine_dm(!!!.x)
  ),
  tar_target(
    indices_clean, 
    clean_indices(indices, file_keyboard, data_validation, device_info)
  )
)
```

```{r run-pipeline, include=FALSE}
tar_make_future(workers = 40)
```
