default:
  # put all the required where filters here
  where:
    # examples (you should make sure these filters are valid):
    # - table: course
    #   field: Name
    #   operator: REGEXP
    #   values: .*
    # - table: content
    #   field: Name
    # # operator of `=` or `IN` can be neglected
    #   values:
    #   - 萤火虫
    #   - 超级秒表
    - table: base_organization
      field: Name
      values: 北京师范大学认知实验
    - table: v_organizationuser
      field: GradeName
      operator: REGEXP
      values: 2.+级
CRTPro:
  game_name: 快速归类PRO
  prep_fun_name: crt
  input: ~
  extra: ~
TOVAS:
  game_name: 捉虫高级简版
  prep_fun_name: cpt
  input: ~
  extra: ~
WxPred:
  game_name: 塔罗牌
  prep_fun_name: countcorrect
  input: ~
  extra: ~
NsymNCmp:
  game_name: 数感
  prep_fun_name: nsymncmp
  input: ~
  extra: ~
Digit3back:
  game_name: 数字卡片
  prep_fun_name: nback
  input: ~
  extra: ~
Grid2back:
  game_name: 格子卡片
  prep_fun_name: nback
  input: ~
  extra: ~
Paint2back:
  game_name: 美术卡片
  prep_fun_name: nback
  input: ~
  extra: ~
Verbal3back:
  game_name: 文字卡片
  prep_fun_name: nback
  input: ~
  extra: ~
Nback3:
  game_name: 魔术师高级
  prep_fun_name: nback
  input: ~
  extra:
    type_signal: stay
StopSigPro:
  game_name: 变色魔块PRO
  prep_fun_name: stopsignal
  input: ~
  extra: ~
ColStrpPro:
  game_name: 多彩文字PRO
  prep_fun_name: congeff
  input: ~
  extra: ~
CardSortPro:
  game_name: 卡片分类PRO
  prep_fun_name: switchcost
  input: ~
  extra: ~
BirdsPro:
  game_name: 候鸟迁徙PRO
  prep_fun_name: complexswitch
  input: ~
  extra: ~
JLO:
  game_name: 方向临摹
  prep_fun_name: jlo
  input: ~
  extra: ~
HOP:
  game_name: 按图索骥
  prep_fun_name: refframe
  input: ~
  extra: ~
MOTPro:
  game_name: 萤火虫PRO
  prep_fun_name: span
  input:
    name_slen: numtarget
  extra: ~
AttSrc:
  game_name: 火眼金睛
  prep_fun_name: countcorrect
  input: ~
  extra: ~
SSTMPro:
  game_name: 位置记忆PRO
  prep_fun_name: span
  input: ~
  extra: ~
LocMemA:
  game_name: 宇宙黑洞A
  prep_fun_name: span
  input:
    name_slen: numobject
  extra: ~
FWSPro:
  game_name: 过目不忘PRO
  prep_fun_name: span
  input: ~
  extra: ~
AscLanMd:
  game_name: 人工语言-中级
  prep_fun_name: countcorrect
  input:
    name_acc: correctness
  extra: ~
LdnTwr:
  game_name: 各得其所
  prep_fun_name: london
  input: ~
  extra: ~
FPTPro:
  game_name: 连点成画PRO
  prep_fun_name: countcorrect
  input:
    name_acc: repetition
  extra: ~
SCSpan:
  game_name: 蝴蝶照相机
  prep_fun_name: span
  input:
    name_acc: accloc
  extra: ~
KeepTrack:
  game_name: 密码箱
  prep_fun_name: span
  input:
    name_slen: length
  extra: ~
SRTPro:
  game_name: 超级秒表PRO
  prep_fun_name: srt
  input: ~
  extra: ~
DualTaskPro:
  game_name: 一心二用PRO
  prep_fun_name: cpt
  input:
    name_type: stimtype
  extra: ~
ConRecA:
  game_name: 连续再认A
  prep_fun_name: cpt
  input: ~
  extra: ~
BPSA:
  game_name: 图片记忆A
  prep_fun_name: bps
  input: ~
  extra: ~
DRM:
  game_name: 言语记忆A
  prep_fun_name: drm
  input: ~
  extra: ~
ProbRL:
  game_name: 强化学习
  prep_fun_name: countcorrect
  input: ~
  extra: ~
Seman:
  game_name: 语义判断
  prep_fun_name: cpt
  input:
    name_type: cresp
  extra:
    type_signal: left
Tone:
  game_name: 声调判断
  prep_fun_name: cpt
  input:
    name_type: cresp
  extra:
    type_signal: left
FlkrPro:
  game_name: 太空飞船PRO
  prep_fun_name: congeff
  input: ~
  extra: ~
FacesPro:
  game_name: 察颜观色PRO
  prep_fun_name: complexswitch
  input: ~
  extra: ~
FDSPro:
  game_name: 顺背数PRO
  prep_fun_name: span
  input: ~
  extra: ~
NVRA:
  game_name: 图形推理A
  prep_fun_name: countcorrect
  input: ~
  extra: ~
DRA:
  game_name: 数字推理A
  prep_fun_name: countcorrect
  input: ~
  extra: ~
VRA:
  game_name: 文字推理A
  prep_fun_name: countcorrect
  input: ~
  extra: ~
MR3DA:
  game_name: 三维心理旋转测试A
  prep_fun_name: countcorrect
  input: ~
  extra: ~
ConRecB:
  game_name: 连续再认B
  prep_fun_name: cpt
  input: ~
  extra: ~
BPSB:
  game_name: 图片记忆B
  prep_fun_name: bps
  input: ~
  extra: ~
DRMB:
  game_name: 言语记忆B
  prep_fun_name: drm
  input: ~
  extra: ~
NVRB:
  game_name: 图形推理B
  prep_fun_name: countcorrect
  input: ~
  extra: ~
DRB:
  game_name: 数字推理B
  prep_fun_name: countcorrect
  input: ~
  extra: ~
VRB:
  game_name: 文字推理B
  prep_fun_name: countcorrect
  input: ~
  extra: ~
MR3DB:
  game_name: 三维心理旋转测试B
  prep_fun_name: countcorrect
  input: ~
  extra: ~
DD:
  game_name: 时长分辨
  prep_fun_name: staircase
  input:
    name_level: variatime
  extra: ~
TOJ:
  game_name: 时间顺序判断
  prep_fun_name: staircase
  input:
    name_level: soa
  extra: ~
RP:
  game_name: 节奏感知
  prep_fun_name: staircase
  input: ~
  extra: ~
CalcSpdMed:
  game_name: 专注大师_中级
  prep_fun_name: countcorrect
  input: ~
  extra: ~
Dual2back:
  game_name: 眼耳并用
  prep_fun_name: nback
  input: ~
  extra: ~
AntiSac:
  game_name: 变戏法
  prep_fun_name: countcorrect
  input: ~
  extra: ~
SchulteMed:
  game_name: 舒尔特方格（中级）
  prep_fun_name: countcorrect2
  input: ~
  extra: ~
AscMem:
  game_name: 欢乐餐厅
  prep_fun_name: countcorrect
  input:
    name_acc: correctness
  extra: ~
NLEMed:
  game_name: 登陆月球（中级）
  prep_fun_name: nle
  input: ~
  extra: ~
CalcMed:
  game_name: 速算师（中级）
  prep_fun_name: countcorrect
  input: ~
  extra: ~
FRA:
  game_name: 图形折叠A
  prep_fun_name: countcorrect
  input: ~
  extra: ~
RATA:
  game_name: 远距离联想A
  prep_fun_name: countcorrect
  input: ~
  extra: ~
OCSpan:
  game_name: 幸运小球
  prep_fun_name: span
  input:
    name_acc: acclet
  extra: ~
RSpan:
  game_name: 打靶场
  prep_fun_name: span
  input:
    name_acc: accarrow
  extra: ~
DirectSrc:
  game_name: 雪花收藏家
  prep_fun_name: countcorrect
  input:
    name_nc: correctnum
    name_ne: falsenum
  extra: ~
Cook:
  game_name: 我是大厨
  prep_fun_name: countcorrect
  input: ~
  extra: ~
FRB:
  game_name: 图形折叠B
  prep_fun_name: countcorrect
  input: ~
  extra: ~
RATB:
  game_name: 远距离联想B
  prep_fun_name: countcorrect
  input: ~
  extra: ~
