---
title: "Pilot in SICNU"
output: html_document
# redirect output to another folder (default is base_dir/output)
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = fs::path(here::here(), "output"),
      ...
    )
  })
---

```{r setup, include=FALSE}
library(targets)
knitr::opts_chunk$set(echo = TRUE, tar_interactive = FALSE)
# targets::tar_unscript()
```

```{targets utils, tar_globals=TRUE, include=FALSE}
combine_dm <- function(...) {
  list(...) |> 
    map(dm::dm_squash_to_tbl, start = "meta") |> 
    bind_rows(.id = "source") |> 
    extract(source, "game_name_abbr", "(?<=_)([^_]+$)")
}
clean_indices <- function(indices) {
  indices |> 
    group_by(user_id, game_name_abbr, game_name, index_name) |> 
    filter(row_number(desc(game_time)) <= 2) |> 
    mutate(
      occasion = case_when(
        str_detect(game_name_abbr, "A$") ~ "test",
        str_detect(game_name_abbr, "B$") ~ "retest",
        row_number(game_time) == 1 ~ "test",
        TRUE ~ "retest"
      ) |> 
        factor(c("test", "retest"))
    ) |> 
    ungroup() |> 
    mutate(across(starts_with("game_name"), ~ str_remove(.x, "[A|B]$"))) |>
    pivot_wider(
      id_cols = c(user_id, game_name, game_name_abbr, index_name), 
      names_from = occasion,
      values_from = score
    )
}
```

```{targets set-globals, tar_globals=TRUE, include=FALSE}
future::plan(future.callr::callr)
games <- tarflow.iquizoo::search_games_mem(config::get("where"))
tar_option_set(
  package = c("tidyverse", "preproc.iquizoo", "tarflow.iquizoo"),
  format = "qs",
  imports = "preproc.iquizoo"
)
targets_data <- tarchetypes::tar_map(
  values = games,
  names = game_name_abbr,
  tar_target(data, pickup(query_tmpl_data, config_where_single_game)),
  tar_target(data_parsed, wrangle_data(data, key)),
  tar_target(
    indices,
    preproc_data(data_parsed, prep_fun, .input = input, .extra = extra)
  ),
  tar_target(
    config_where_single_game,
    insert_where_single_game(config_where, game_id)
  ),
  tar_target(
    input,
    config::get("input", config = game_name_abbr, file = file_config)
  ),
  tar_target(
    extra,
    config::get("extra", config = game_name_abbr, file = file_config)
  )
)
```

```{targets load-config, include=FALSE}
list(
  tar_target(file_config, "config.yml", format = "file"),
  tar_target(config_where, config::get("where", file = file_config))
)
```

```{targets download-users, include=FALSE}
list(
  tar_target(query_tmpl_users, fs::path("sql", "users.tmpl.sql"), format = "file"),
  tar_target(users, tarflow.iquizoo::pickup(query_tmpl_users, config_where))
)
```

```{targets data-and-scores, include=FALSE}
list(
  tar_target(query_tmpl_data, fs::path("sql", "data.tmpl.sql"), format = "file"),
  tar_target(key, ".id"),
  targets_data,
  tarchetypes::tar_combine(
    indices, 
    targets_data[[3]],
    command = combine_dm(!!!.x)
  ),
  tar_target(indices_clean, clean_indices(indices))
)
```

```{r run-pipeline, include=FALSE}
tar_make_future(workers = 20)
```
