---
title: "Test Performance Checking"
author: "Liang Zhang"
date: "2022-01-18"
output: 
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(targets)
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
tar_config_set(store = here::here("bnu/_targets"))
```

```{r load-data, cache=TRUE}
tests_keyboard <- read_lines(here::here("config/require_keybord.txt"))
validation <- tar_read(device_info) |> 
  mutate(valid_device = !(game_name %in% tests_keyboard & used_mouse)) |> 
  inner_join(tar_read(data_validation)) |> 
  filter(valid_device & valid_version) |> 
  group_by(user_id, game_name) |> 
  filter(
    if_else(
      str_detect(game_name_abbr, "[A|B]$"), 
      row_number(desc(game_time)) == 1,
      row_number(desc(game_time)) <= 2
    )
  ) |> 
  ungroup()
indices <- tar_read(indices) |> 
  semi_join(validation) |> 
  mutate(across(starts_with("game_name"), ~ str_remove(.x, "[A|B]$"))) |> 
  group_by(user_id, game_name_abbr, game_name, index_name) |> 
  mutate(occasion = recode(row_number(game_time), `1` = "test", `2` = "retest")) |> 
  ungroup() |> 
  pivot_wider(
    id_cols = c(user_id, game_name, game_name_abbr, index_name), 
    names_from = occasion,
    values_from = score
  )
tests_included <- deframe(distinct(indices, game_name_abbr, game_name))
```

```{r render-content, results='asis'}
render_content <- function(file, ...) {
  knitr::knit(
    text = knitr::knit_expand(file, ...),
    quiet = TRUE
  )
}
purrr::imap_chr(
  tests_included,
  ~ render_content(
    file = here::here("archetypes/child_check_index.Rmd"),
    game_name_abbr = .x,
    game_name = .y
  )
) |> 
  str_c(collapse = "\n\n") |> 
  cat()
```
